# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mywebapi:
    image: mywebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

    environment:
      - ASPNETCORE_URLS=http://+:8080
